### ISSUE TITLE
Document how to use exometer_report:subscribe() with "raw" processes

### ISSUE THREAD

**Issue by nifoc** [Feuerlabs/exometer#62]
The README and the `exometer_report` documentation make various references to what happens when `exometer_report` is used with processes (as opposed to modules that implement the behaviour).

There is no documentation on how to use just processes (without the bahaviour). If there is, then I was unable to find it.

**Comment by tolbrino** [comment]
I don't think creating reporters without using `exometer_report` is something we should encourage as this would circumvent the whole point of having `exometer_report`. However, if you are interesting in finding our more about the actual messages a reporter needs to handle, take a look at https://github.com/Feuerlabs/exometer_core/blob/master/src/exometer_report.erl#L1540

I'm closing this issue since the topic is now more related to `exometer_core`. Feel free to open a new discussion there.
