### ISSUE TITLE
Debug log is cluttered by collectd entries.

### ISSUE THREAD

**Issue by sylane** [Feuerlabs/exometer#68]
When enabling debug logging, collectd reporter write 3 lines every time it publishes a datapoint. This is cluttering the log and making it unusable for debugging anything else.

Is there a way to selectively remove the logging from a module with lager ?

If not, how would you want it to be changed ? Some conditional compilation flag ?

Thank you.

**Comment by tolbrino** [comment]
@sylane The `collectd` reporter was moved into its own repository at https://github.com/Feuerlabs/exometer_collectd as part of the `exometer` and `exometer_core` split. I don't think the logging has been changed since your initial comment, so feel free to add some configuration to the reporter to mitigate the debug log flooding.
